import { Headers } from '@/components/Headers/Headers';
import './globals.css';
import { Plus_Jakarta_Sans } from 'next/font/google';
import Footer from '@/components/footer/Footer';

const jakarta = Plus_Jakarta_Sans({ subsets: ['latin'] });

export const metadata = {
  title: 'VPapell',
  description: 'Generated by create next app',
  icons: {
    icon: '/issets/imageHeaders/vpapelicoAzul.png',
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body className={jakarta.className}>
        <Headers />
        {children}
        <Footer />
      </body>
    </html>
  );
}
