import { Headers } from '@/components/Headers/Headers';
import './globals.css';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'VPapel',
  description: 'Generated by create next app',
  icons: {
    icon: '/issets/imageHeaders/vpapelico.png',
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body className="">
        <Headers />
        {children}
      </body>
    </html>
  );
}
